"""Scene approval workflow CLI commands.

Commands:
    ytfactory scene list   <project-id>           — show all scene states
    ytfactory scene approve <project-id> <scene>  — approve a scene
    ytfactory scene reject  <project-id> <scene>  — mark Needs Revision
    ytfactory scene lock    <project-id> <scene>  — lock (prevent auto-regen)
    ytfactory scene unlock  <project-id> <scene>  — unlock a locked scene
    ytfactory scene review  <project-id>          — write scene-review.md
"""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from ytfactory.incremental.models import SceneState
from ytfactory.incremental.scene_workspace import SceneWorkspace
from ytfactory.shared.constants import WORKSPACE_DIR

console = Console()

scene_app = typer.Typer(
    help=(
        "Scene approval workflow — review, approve, lock, and manage per-scene states.\n\n"
        "States: Draft → Needs Review → Approved → Locked\n\n"
        "A Locked scene is never auto-regenerated by --resume or --force-* runs.\n"
        "Only 'scene unlock' or --force-scene N overrides it.\n\n"
        "Examples:\n\n"
        "  ytfactory scene list abc123\n\n"
        "  ytfactory scene approve abc123 3\n\n"
        "  ytfactory scene reject abc123 8 --notes 'background wrong'\n\n"
        "  ytfactory scene lock abc123 5\n\n"
        "  ytfactory scene review abc123"
    )
)


def _project_dir(project_id: str) -> Path:
    return Path(WORKSPACE_DIR) / project_id


def _workspace(project_id: str) -> SceneWorkspace:
    return SceneWorkspace(_project_dir(project_id))


_STATE_COLOR: dict[SceneState, str] = {
    SceneState.DRAFT: "dim",
    SceneState.NEEDS_REVIEW: "cyan",
    SceneState.NEEDS_REVISION: "yellow",
    SceneState.APPROVED: "green",
    SceneState.LOCKED: "magenta",
}

_STATE_ICON: dict[SceneState, str] = {
    SceneState.DRAFT: "○",
    SceneState.NEEDS_REVIEW: "👁",
    SceneState.NEEDS_REVISION: "⚠",
    SceneState.APPROVED: "✓",
    SceneState.LOCKED: "🔒",
}


@scene_app.command(name="list")
def scene_list(
    project_id: str = typer.Argument(..., help="Project ID"),
) -> None:
    """List all scenes and their approval states."""
    ws = _workspace(project_id)
    states = ws.all_states()

    if not states:
        console.print("[dim]No scenes found — run plan-scenes first.[/dim]")
        raise typer.Exit()

    table = Table(title=f"Scene Workspace — {project_id}", show_lines=False)
    table.add_column("Scene", style="bold", width=8)
    table.add_column("State", width=18)
    table.add_column("Notes")

    for idx in sorted(states):
        state = states[idx]
        notes = ws.get_notes(idx)
        icon = _STATE_ICON.get(state, "?")
        color = _STATE_COLOR.get(state, "white")
        table.add_row(
            f"{idx:03d}",
            f"[{color}]{icon} {state.value}[/{color}]",
            notes or "",
        )

    console.print(table)


@scene_app.command(name="approve")
def scene_approve(
    project_id: str = typer.Argument(..., help="Project ID"),
    scene: int = typer.Argument(..., help="Scene index (e.g. 3)"),
) -> None:
    """Approve a scene for final rendering."""
    ws = _workspace(project_id)
    if ws.is_locked(scene):
        console.print(
            f"[magenta]Scene {scene:03d} is locked — already approved + locked.[/magenta]"
        )
        raise typer.Exit()
    ws.set_state(scene, SceneState.APPROVED)
    console.print(f"[green]✓ Scene {scene:03d} approved.[/green]")


@scene_app.command(name="reject")
def scene_reject(
    project_id: str = typer.Argument(..., help="Project ID"),
    scene: int = typer.Argument(..., help="Scene index (e.g. 3)"),
    notes: str = typer.Option("", "--notes", "-n", help="Reason for rejection"),
) -> None:
    """Mark a scene as Needs Revision."""
    ws = _workspace(project_id)
    if ws.is_locked(scene):
        console.print(
            f"[red]Scene {scene:03d} is locked — cannot reject a locked scene.[/red]"
        )
        raise typer.Exit(1)
    ws.set_state(scene, SceneState.NEEDS_REVISION, notes=notes)
    console.print(f"[yellow]⚠ Scene {scene:03d} marked Needs Revision.[/yellow]")
    if notes:
        console.print(f"  Notes: {notes}")


@scene_app.command(name="lock")
def scene_lock(
    project_id: str = typer.Argument(..., help="Project ID"),
    scene: int = typer.Argument(..., help="Scene index (e.g. 3)"),
) -> None:
    """Lock a scene — prevents auto-regeneration."""
    ws = _workspace(project_id)
    ws.set_state(scene, SceneState.LOCKED)
    console.print(f"[magenta]🔒 Scene {scene:03d} locked.[/magenta]")


@scene_app.command(name="unlock")
def scene_unlock(
    project_id: str = typer.Argument(..., help="Project ID"),
    scene: int = typer.Argument(..., help="Scene index (e.g. 3)"),
) -> None:
    """Unlock a locked scene (returns to Approved state)."""
    ws = _workspace(project_id)
    if not ws.is_locked(scene):
        console.print(f"[dim]Scene {scene:03d} is not locked.[/dim]")
        raise typer.Exit()
    ws.set_state(scene, SceneState.APPROVED)
    console.print(f"[green]Scene {scene:03d} unlocked → Approved.[/green]")


@scene_app.command(name="review")
def scene_review(
    project_id: str = typer.Argument(..., help="Project ID"),
) -> None:
    """Write scene-review.md and print a summary to the console."""
    from ytfactory.incremental.engine import IncrementalBuildEngine

    project = _project_dir(project_id)
    engine = IncrementalBuildEngine(project)
    out = engine.write_scene_review_md()
    console.print(f"[green]✓[/green] Scene review written → [bold]{out}[/bold]")

    # Print a quick state summary
    ws = engine.workspace
    states = ws.all_states()
    counts: dict[str, int] = {}
    for s in states.values():
        counts[s.value] = counts.get(s.value, 0) + 1

    for state_val, count in sorted(counts.items()):
        try:
            st = SceneState(state_val)
            color = _STATE_COLOR.get(st, "white")
            icon = _STATE_ICON.get(st, "?")
            console.print(f"  [{color}]{icon} {state_val}: {count}[/{color}]")
        except ValueError:
            console.print(f"  ? {state_val}: {count}")
