"""
ASSWriter — serialize SubtitleCue objects to Advanced SubStation Alpha format.

ASS file structure:
  [Script Info]     — metadata + resolution
  [V4+ Styles]      — font, colors, margins, positioning
  [Events]          — subtitle cue timings and text

Multi-line cues use the ASS hard line break \\N (backslash + capital N).
Timestamps use ASS format: H:MM:SS.cc (centiseconds, not milliseconds).

Color encoding: &HAABBGGRR
  Alpha channel: 00 = fully opaque, FF = fully transparent

ASS files are UTF-8 with no BOM (FFmpeg compatibility).
"""

from __future__ import annotations

from ..models import SubtitleCue
from .style_builder import ASSStyleBuilder
from .theme import ASSTheme
from .theme_manager import ThemeManager

# Wrap mode 0 = smart wrap (subtitle standard)
_WRAP_STYLE = 0

_EVENTS_HEADER = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
)


class ASSWriter:
    """Serialize SubtitleCue objects into a complete ASS file."""

    def __init__(self, theme: ASSTheme | None = None) -> None:
        self._theme = theme or ThemeManager.get("default")
        self._style_builder = ASSStyleBuilder()

    # ── Public API ────────────────────────────────────────────────────────────

    def write(self, cues: list[SubtitleCue]) -> str:
        """
        Produce a complete ASS file string from cue list.

        Returns empty string when the cue list is empty.
        """
        if not cues:
            return ""

        sections = [
            self._script_info(),
            "",
            self._style_builder.build_section(self._theme),
            "",
            self._events_section(cues),
        ]
        return "\n".join(sections)

    # ── Section builders ─────────────────────────────────────────────────────

    def _script_info(self) -> str:
        t = self._theme
        lines = [
            "[Script Info]",
            "; Generated by YouTube Factory — ASS Subtitle Engine V1",
            "ScriptType: v4.00+",
            f"WrapStyle: {_WRAP_STYLE}",
            "ScaledBorderAndShadow: yes",
            f"PlayResX: {t.play_res_x}",
            f"PlayResY: {t.play_res_y}",
            "Timer: 100.0000",
        ]
        return "\n".join(lines)

    def _events_section(self, cues: list[SubtitleCue]) -> str:
        lines = ["[Events]", _EVENTS_HEADER]
        for cue in cues:
            text = r"\N".join(line for line in cue.lines if line.strip())
            if not text:
                continue
            lines.append(self._dialogue_line(cue, text))
        return "\n".join(lines)

    def _dialogue_line(self, cue: SubtitleCue, text: str) -> str:
        """
        Produce one Dialogue: line for a cue.

        Multi-line cues use \\N (hard break) — no wrapping ambiguity.
        MarginL/R/V are zero — positioning comes from the Style.
        """
        start = _fmt_ass_time(cue.start)
        end = _fmt_ass_time(cue.end)
        return f"Dialogue: 0,{start},{end},Default,,0,0,0,,{text}"


# ── Helpers ───────────────────────────────────────────────────────────────────


def _fmt_ass_time(seconds: float) -> str:
    """
    Format a timestamp for ASS: H:MM:SS.cc (centiseconds).

    Handles scenes longer than one hour.
    Clamps centiseconds to [0, 99] to prevent rounding to 100.
    """
    if seconds < 0:
        seconds = 0.0
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int(round((seconds % 1) * 100))
    if cs >= 100:
        cs = 99
        s = min(s + 1, 59)
    return f"{h:d}:{m:02d}:{s:02d}.{cs:02d}"
